AWSTemplateFormatVersion: "2010-09-09"
  Transform: "AWS::Serverless-2016-10-31"
  Description: CD Demo Lambda
  Resources:
    a2role:
      Type : 'AWS::IAM::Role'
      Properties : 
        AssumeRolePolicyDocument : 
          Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Principal: 
                  Service: 
                    - lambda.amazonaws.com
                Action:
                    - 'sts:AssumeRole'
              
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AmazonESFullAccess'
          - 'arn:aws:iam::aws:policy/AmazonLexFullAccess'
          - 'arn:aws:iam::aws:policy/AmazonRekognitionFullAccess'
          - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
          - 'arn:aws:iam::aws:policy/CloudWatchEventsFullAccess'
      
        Policies: 
            - PolicyName: BasicLogs
              PolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                  - Effect: Allow
                    Action: 'logs:CreateLogGroup'
                    Resource: 'arn:aws:logs:us-east-1:642155208155:*'
                  - Effect: 'Allow'
                    Action: 
                      - 'logs:CreateLogStream'
                      - 'logs:PutLogEvents'
                    Resource: 
                      - 'arn:aws:logs:us-east-1:642155208155:log-group:/aws/lambda/lf1_a2:*'
        Description : 'Allows all required access'
        RoleName : "Lambda_access_all"

    CDDemoLambda1:
      Type: "AWS::Serverless::Function"
      Properties:
        FunctionName: search-photos-2
        Handler: lambda_function.lambda_handler
        Runtime: python3.6
        CodeUri: ./search-photos-copy
        Description: "Lambda function for CD Demo"
        MemorySize: 128
        Timeout: 30
        Role: !Ref a2role
        Environment:
          Variables:
            REGION: us-east-1
    CDDemoLambda2:
      Type: "AWS::Serverless::Function"
      Properties:
        FunctionName: index-photos-2
        Handler: lambda_function.lambda_handler
        Runtime: python3.6
        CodeUri: ./index-photos-copy
        Description: "Lambda function for CD Demo"
        MemorySize: 128
        Timeout: 30
        Role: !Ref a2role
        Environment:
          Variables:
            REGION: us-east-1
